export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const REQUEST_PROFILES = 'REQUEST_PROFILES';
export const RECEIVE_PROFILES = 'RECEIVE_PROFILES';
export const GET_USER_ID = 'GET_USER_ID';
export const UPDATE_PROFILES = 'UPDATE_PROFILES';